blue_prints/OPCUA/index/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config['SECRET_KEY'] = 'f1d9d48ec0e26e2a250839fa36ea2c602cc4f85ccfeb5c65'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
from flask_wtf.csrf import CSRFProtect
csrf = CSRFProtect(app)
db = SQLAlchemy(app)

from index import routes

blue_prints/OPCUA/index/routes.py
from flask import (render_template, flash, url_for, jsonify,request,redirect)
from index import app,db
from index.models import Server,Object, Variable
from index.forms import ServerCreateForm,ObjectCreateForm,VariableCreateForm
from . import utils
from myserver import MyServer
from myplc import MyPlc
from snap7.snap7exceptions import Snap7Exception
import time

class Control(MyServer,MyPlc):
    def __init__(self):
        self.ip = None        

    def get_db(self, server_id,ip=None):
        self.db_server = Server.query.get(server_id)
        if ip is not None:
            self.ip = ip
        self.inits()
    
    def inits(self):
        MyServer.__init__(self)
        MyPlc.__init__(self)
    
    def set_opc(self):
        self.instantiate_server_vars()

    def make_tags_dict(self,allvars):
        for var in allvars:
            self.varsdict[var.variable_address] = {
                'obj'   : self.opc_variables_dict[var.variable_address],
                'type'  : var.variable_type
            }

# global ms,mp
global ctrl
ctrl = Control()

@app.route("/")
def home():
    servers = Server.query.all()
    form = ServerCreateForm()
    return render_template('index.html',form=form,servers=servers)

@app.route("/",methods= ['POST','GET'] )
def create_server():
    form = ServerCreateForm()
    if form.validate_on_submit():
        server = Server( server_name=form.server_name.data, 
        server_endpoint_url=form.endpoint_url.data,server_namespace=form.namespace.data )
        db.session.add(server)
        db.session.commit()
        resp = {
            'message' : '{} Created Successfully'.format(form.server_name.data),
            'servers' : Server.query.all()
        }
        return redirect(url_for('home'))
    return jsonify(data=form.errors)

@app.route("/server/<serverid>/edit",methods= ['POST'] )    
def edit_server( serverid ):
    form = ServerCreateForm()
    if form.validate_on_submit():
        server = Server.query.get( serverid )
        server.server_name = form.server_name.data
        server.server_endpoint_url = form.endpoint_url.data
        server.server_namespace = form.namespace.data
        db.session.add( server )
        db.session.commit()
        flash('{} Edited Successfully'.format(server.server_name), 'success')
        return redirect(url_for('home'))
    flash('Could not edit Server' 'danger')
    return redirect(url_for('home'))            

@app.route("/server/delete/<serverid>",methods= ['POST'] )    
def delete_server( serverid ):
    server = Server.query.get( serverid )
    servername = server.name
    db.session.delete(server)
    db.session.commit()
    flash('{} Deleted Successfully'.format(servername), 'success')
    return redirect(url_for('create_server'))


@app.route("/server/<serverid>",methods= ['GET'] )
def server_populate(serverid):
    server = Server.query.get( serverid )
    objform = ObjectCreateForm()
    varform = VariableCreateForm()
    objects = server.server_objects
    varform.var_object.choices = utils.selectVals(objects)
    # objform.parent_object.choices = selectVals(objects)
    # vars = server.server_objects
    return render_template('server.html',
             objects=objects,
             server=server, 
             objform = ObjectCreateForm(),
             varform=varform
    )
@app.route("/start_server/<serverid>",methods=['POST'])
def start_server(serverid):
    if request.method=='POST' and request.form: 
        server = Server.query.get(request.form['server'])
        ctrl.get_db(server.id)
        try:
            ctrl.opc_server.start()
        except OSError as ipexp:
            return jsonify({ 'warning':'The endpoint: {} is currently being used'.format(server.server_endpoint_url) })
        else:     
            ctrl.connections()            
            return jsonify({ 'success':'PLC Connected' })

        return jsonify({ 'success':'Server running at {}'.format( server.server_endpoint_url ) })

    else:
        return jsonify("Web Server Error")


@app.route("/stop_server/<serverid>",methods=['GET'])
def stop_server(serverid):
    server = Server.query.get( serverid )
    ctrl.kill_threads()
    ctrl.opc_server.stop()
    return jsonify({"info":"Server at {} Stopped".format(server.server_endpoint_url)})
    


@app.route("/create_object",methods= ['POST'] )
def create_object():
    objform = ObjectCreateForm()
    
    serverobj = Server.query.get(objform.server.data)
    if request.method=='POST' and request.form:        
        obj = Object(   object_name = request.form['object_name'],
                        object_parent_id = request.form['parent_object'] if request.form['parent_object'] else None,
                        server = Server.query.get(request.form['server']) 
                    )
        db.session.add(obj)
        db.session.commit()
        return redirect( url_for('server_populate',serverid=serverobj.id) )
    else:    
        flash('Could not create {} object'.format(objform.object_name))
        return redirect(url_for('server_populate',serverid=serverobj.id))


@app.route("/create_variable,<server_id>/",methods= ['POST'] )
def create_variable(server_id):
    varform = VariableCreateForm()
    # obj = Object.query.get(varform.var_object.data)
    if utils.custom_validation( varform.data ):                
        if Variable.validate(varform.var_object.data,varform.address.data):
            try:
                var = Variable( variable_name=varform.name.data, variable_type=varform.var_type.data,
                        variable_writable=varform.writable.data, variable_address=varform.address.data,
                        variable_value=varform.value.data, object=Object.query.get(varform.var_object.data),
                         )
            except AttributeError as aexp:
                flash('Ensure all fields are filled','warning')                         
                return redirect( url_for('server_populate',serverid=server_id) )                             
        else:
            flash('The address {} has already been taken'.format(varform.address.data),'warning')                         
            return redirect( url_for('server_populate',serverid=server_id) )                         

        
        try:
            db.session.add(var)
            db.session.commit() 
        except AttributeError as aexp:
            flash('Ensure all fields are filled','warning')                         
            return redirect( url_for('server_populate',serverid=server_id) )                   
        except Exception as exp:
            flash('Could not save Variable'.format(varform.name.data))                
        else:
            flash('{} Created Successfully'.format(var.variable_name),'success')
            return redirect(url_for('server_populate',serverid=server_id))
            
    else:    
        flash( 'Could not create {} Variable'.format(varform.name.data), 'danger' )
        return redirect(url_for('server_populate',serverid=server_id))


@app.route("/variables/<var_id>/delete",methods= ['GET'] )
def delete_var(var_id):
    var = Variable.query.get(var_id)
    db.session.delete(var)
    db.session.commit()
    return jsonify("Deleted Successfully")

@app.route("/delete_object",methods= ['POST'] )
def delete_object():
    obj = Object.query.get(request.form['object_id'])
    objName = obj.name
    server_id = request.form['server_id']

    db.session.delete( obj )
    db.session.commit()
    flash('{} Deleted SUccessfully'.format(objName), 'success')
    return redirect(url_for('server_populate',serverid=server_id))
    

blueprints/opcua.py
from blueprints.influxdb import *
from blueprints.login import is_login
from flask import jsonify

opcua_ = Blueprint("opcua_",__name__)


from blueprints.forms import ServerCreateForm
'''
opcua库文件 本路由开发中 
'''
# from flask_wtf.csrf import CSRFProtect
# csrf = CSRFProtect()

from index import db
from index.models import Server, Object, Variable
from index.forms import ServerCreateForm, ObjectCreateForm, VariableCreateForm
from blueprints.OPCUA.index import utils
from myserver import MyServer
from myplc import MyPlc
from snap7.snap7exceptions import Snap7Exception
import time


class Control(MyServer, MyPlc):
    def __init__(self):
        self.ip = None

    def get_db(self, server_id, ip=None):
        self.db_server = Server.query.get(server_id)
        if ip is not None:
            self.ip = ip
        self.inits()

    def inits(self):
        MyServer.__init__(self)
        MyPlc.__init__(self)

    def set_opc(self):
        self.instantiate_server_vars()

    def make_tags_dict(self, allvars):
        for var in allvars:
            self.varsdict[var.variable_address] = {
                'obj': self.opc_variables_dict[var.variable_address],
                'type': var.variable_type
            }


# global ms,mp
global ctrl
ctrl = Control()

@is_login
@opcua_.route("/", methods=['POST', 'GET'])
def create_server():
    form = ServerCreateForm()
    if form.validate_on_submit():
        server = Server(server_name=form.server_name.data,
                        server_endpoint_url=form.endpoint_url.data, server_namespace=form.namespace.data)
        db.session.add(server)
        db.session.commit()
        resp = {
            'message': '{} Created Successfully'.format(form.server_name.data),
            'servers': Server.query.all()
        }
        return redirect(url_for('home'))
    return jsonify(data=form.errors)

@is_login
@opcua_.route("/server/<serverid>/edit", methods=['POST'])
def edit_server(serverid):
    form = ServerCreateForm()
    if form.validate_on_submit():
        server = Server.query.get(serverid)
        server.server_name = form.server_name.data
        server.server_endpoint_url = form.endpoint_url.data
        server.server_namespace = form.namespace.data
        db.session.add(server)
        db.session.commit()
        flash('{} Edited Successfully'.format(server.server_name), 'success')
        return redirect(url_for('home'))
    flash('Could not edit Server' 'danger')
    return redirect(url_for('home'))

@is_login
@opcua_.route("/server/delete/<serverid>", methods=['POST'])
def delete_server(serverid):
    server = Server.query.get(serverid)
    servername = server.name
    db.session.delete(server)
    db.session.commit()
    flash('{} Deleted Successfully'.format(servername), 'success')
    return redirect(url_for('create_server'))

@is_login
@opcua_.route("/server/<serverid>", methods=['GET'])
def server_populate(serverid):
    server = Server.query.get(serverid)
    objform = ObjectCreateForm()
    varform = VariableCreateForm()
    objects = server.server_objects
    varform.var_object.choices = utils.selectVals(objects)
    # objform.parent_object.choices = selectVals(objects)
    # vars = server.server_objects
    return render_template('server.html',
                           objects=objects,
                           server=server,
                           objform=ObjectCreateForm(),
                           varform=varform
                           )

@is_login
@opcua_.route("/start_server/<serverid>", methods=['POST'])
def start_server(serverid):
    if request.method == 'POST' and request.form:
        server = Server.query.get(request.form['server'])
        ctrl.get_db(server.id)
        try:
            ctrl.opc_server.start()
        except OSError as ipexp:
            return jsonify({'warning': 'The endpoint: {} is currently being used'.format(server.server_endpoint_url)})
        else:
            ctrl.connections()
            return jsonify({'success': 'PLC Connected'})

        return jsonify({'success': 'Server running at {}'.format(server.server_endpoint_url)})

    else:
        return jsonify("Web Server Error")

@is_login
@opcua_.route("/stop_server/<serverid>", methods=['GET'])
def stop_server(serverid):
    server = Server.query.get(serverid)
    ctrl.kill_threads()
    ctrl.opc_server.stop()
    return jsonify({"info": "Server at {} Stopped".format(server.server_endpoint_url)})

@is_login
@opcua_.route("/create_object", methods=['POST'])
def create_object():
    objform = ObjectCreateForm()

    serverobj = Server.query.get(objform.server.data)
    if request.method == 'POST' and request.form:
        obj = Object(object_name=request.form['object_name'],
                     object_parent_id=request.form['parent_object'] if request.form['parent_object'] else None,
                     server=Server.query.get(request.form['server'])
                     )
        db.session.add(obj)
        db.session.commit()
        return redirect(url_for('server_populate', serverid=serverobj.id))
    else:
        flash('Could not create {} object'.format(objform.object_name))
        return redirect(url_for('server_populate', serverid=serverobj.id))

@is_login
@opcua_.route("/create_variable,<server_id>/", methods=['POST'])
def create_variable(server_id):
    varform = VariableCreateForm()
    # obj = Object.query.get(varform.var_object.data)
    if utils.custom_validation(varform.data):
        if Variable.validate(varform.var_object.data, varform.address.data):
            try:
                var = Variable(variable_name=varform.name.data, variable_type=varform.var_type.data,
                               variable_writable=varform.writable.data, variable_address=varform.address.data,
                               variable_value=varform.value.data, object=Object.query.get(varform.var_object.data),
                               )
            except AttributeError as aexp:
                flash('Ensure all fields are filled', 'warning')
                return redirect(url_for('server_populate', serverid=server_id))
        else:
            flash('The address {} has already been taken'.format(varform.address.data), 'warning')
            return redirect(url_for('server_populate', serverid=server_id))

        try:
            db.session.add(var)
            db.session.commit()
        except AttributeError as aexp:
            flash('Ensure all fields are filled', 'warning')
            return redirect(url_for('server_populate', serverid=server_id))
        except Exception as exp:
            flash('Could not save Variable'.format(varform.name.data))
        else:
            flash('{} Created Successfully'.format(var.variable_name), 'success')
            return redirect(url_for('server_populate', serverid=server_id))

    else:
        flash('Could not create {} Variable'.format(varform.name.data), 'danger')
        return redirect(url_for('server_populate', serverid=server_id))

@is_login
@opcua_.route("/variables/<var_id>/delete", methods=['GET'])
def delete_var(var_id):
    var = Variable.query.get(var_id)
    db.session.delete(var)
    db.session.commit()
    return jsonify("Deleted Successfully")

@is_login
@opcua_.route("/delete_object", methods=['POST'])
def delete_object():
    obj = Object.query.get(request.form['object_id'])
    objName = obj.name
    server_id = request.form['server_id']

    db.session.delete(obj)
    db.session.commit()
    flash('{} Deleted SUccessfully'.format(objName), 'success')
    return redirect(url_for('server_populate', serverid=server_id))


######################## OPC UA Client 用于写入InfluxDB #################################### ToDo
@opcua_.route("/opcua")
@is_login
def opcua():
    # return render_template("b.html")
    form = ServerCreateForm()
    return render_template("opcua.html",form=form)

######################## OPC UA Server 用于转换为OPC UA格式数据
# basic server仅支持UA expert Prosys还不支持 ########################
@opcua_.route("/opcuaserver")
@is_login
def opcuaserver():
    # return render_template("b.html")
    return render_template("opcua.html")


# @opcua_.route("/o",methods=['GET','POST'])
# @is_login
# def create_server():
#     print('create-server')
#     # return render_template("b.html")
#     return redirect('opcua')

blueprints/opcua/index/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config['SECRET_KEY'] = 'f1d9d48ec0e26e2a250839fa36ea2c602cc4f85ccfeb5c65'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
from flask_wtf.csrf import CSRFProtect
csrf = CSRFProtect(app)
db = SQLAlchemy(app)

from index import routes

templates/base backup/base.html
<!doctype html>
<html>
<!-- template for 多协议数据采集配置界面 保持风格和主要元素统一 
	包括 head 导航栏、页脚、content下移60px InfluxBD配置  框架模板，应用还不够彻底 比如表格框架-->

<head>
	{% block head %}
	<link href="/static/favicon.ico" rel="SHORTCUT ICON" />
	<link rel="apple-touch-icon" href="static/ico.jpg">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- chrome 窗口化 地址栏颜色 -->
	<meta name="msapplication-TileColor" content="#1b3075">
	<!-- 苹果是否启用全屏模式 -->
	<meta name="apple-mobile-web-app-capable" content="yes">
	<!-- 安卓 主屏幕应用全屏 -->
	<meta name="mobile-web-app-capable" content="yes">　　
	<!-- 全屏时状态 颜色设置 -->
	<meta name="apple-mobile-web-status-bar-style" content="black">

	<title>数据采集系统-{% block title %}{% endblock %}</title>
	{% endblock %}

	<meta name="description" content="Flask Based SCADA">
	<meta name="Su600" content="Su600">

	<link href="/static/css/bootstrap.min.css" rel="stylesheet">
	<link href="/static/css/style.css" rel="stylesheet">

</head>

<body>
	<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top " id="导航栏">
		<a class="navbar-brand" href="#">
			<img src="/static/avic.png" width="35px">
		</a>
		<a class="navbar-brand" href="/#">Home</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="collapsibleNavbar">
			<nav class="nav justify-content-center">
				{% block navlist %} {% endblock navlist %}
				<a class="btn btn-dark" href="/logout">Logout</a>
		</div>
	</nav>

	<div id="content" style="padding-top: 60px; margin: 10px;">
		{% block content %}{% endblock %}
	</div>

	<div class="container-fluid " style="color: white;" id="influxdbsetting">
		<div class="container-fluid" style="margin:0px;padding:30px ; background:rgb(2, 70, 148);">
			<form class="form-inline " style="padding: 20px" method="POST">
				<div class='form-row'>
										
					<label for="influxdb">
						<h5>InfluxDB地址：</h5>
					</label>
					<input type="text" name="influxdb" id="influxdb" class="form-control" placeholder=""
						aria-describedby="InfluxDB">

					<label for="token">
						<h5>Token：</h5>
					</label>
					<input type="password" name="token" id="token" class="form-control" placeholder=""
						aria-describedby="InfluxDB">

					<label for="measurement">
						<h5>Measurement：</h5>
					</label>
					<input type="text" name="measurement" id="measurement" class="form-control" placeholder="设备名称"
						aria-describedby="InfluxDB">
				</div>

				<div class='form-row' >
				<label for="cycle" >
					<h5>采集周期(秒)：</h5>
				</label>
				<input style="padding-block :30px; margin: 10px 0px; " type="text" name="cycle" id="cycle" class="form-control" placeholder="1">

				<button class="btn btn-primary form-control" href="#influxdbsetting"
					style="padding-block :30px; margin: 10px; " type="submit" name="Action" value="influxdb"
					id="startinfluxdb"> 开始写入 </button>
				<!-- 开始写入后应禁用写入按钮 在页面上方显示运行状态 根据表单字典长度区分表单提交按钮-->
				<a class="btn btn-danger form-control" style="padding-block: 30px; margin: 10px; " type="button"
					role="button"> 停止写入 </a>
				</div>
				{% with messages = get_flashed_messages(category_filter=["influx"]) %}
				{% if messages %}
				{% for message in messages %}
				{% if message%}
				<p><span class="badge badge-success">InfluxDB Running</span></p>
				{% endif %}
				{% endfor %}
				{% endif %}
				{% endwith %}

			</form>
		</div>

	</div>

	<div class="container-fluid" style="height:20px;padding-top: 30px;">
		<!--<h2>混合色彩进度条</h2>-->
		<!--<p>进度条可以设置多种颜色:</p> -->
		<div class="progress" style="height:10px; ">
			<div class="progress-bar" style="width:33.33%">
			</div>
			<div class="progress-bar bg-warning" style="width:33.33%">
			</div>
			<div class="progress-bar bg-danger" style="width:33.33%">
			</div>
		</div>
	</div>

	<div class="container-fluid" style="height:50px;">
		<footer style="text-align:center ">
			<p style="padding-top:25px">
				Copyright © 2020 Su600, Inc.
			</p>
		</footer>
	</div>
</body>

<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/scripts.js"></script>

</html>

templates/base backup/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="#" method="post">
        <p>提交：<input type="text" name="username" ></p>
        <p>密码：<input type="password" name="password" ></p>
        <!--<button type="submit">提交</button>-->
        <button type="submit">测试</button>
        <button type="submit">测试</button>
    </form>
</body>
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/scripts.js"></script>

</html>

templates/base backup/opcua.html
{% extends "base.html" %}
{% block title %}OPC UA{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}

{% block navlist %}
<a class="btn btn-dark" href="setting">Back to Setting</a>
{% endblock navlist %}

{% block content %}
<div class="container-fluid">
    <div class="jumbotron jumbotron-fluid" style="background-color: rgba(231, 231, 233, 0.746);padding:20px">
        <div class="row">
            <div class="col-md-5" style="text-align: justify;">
                <img class="img-fluid" src="static/opcua.png" alt="Opcua" />
            </div>
            <div class="col-md-6">
                <strong>
                    基于Python-OPC UA构建Server
                </strong>
            </div>
        </div>
    </div>
</div>

<div id="alerts-wrapper" class="">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div id="alert-message" class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>

<div class="container-fluid">
    <h4>OPC UA Server配置</h4>
    <!-- Edit Server Modal -->
<div class="modal fade" id="edit-server-modal" style="margin: 10px;" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="edit_projects_form" class="d-block mb-3 form-inline" method="post" action="" autocomplete=false>
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">OPC UA Server配置</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form.hidden_tag() }}
                    <div class="form-row">
                        {{ form.server_name.label( class="form-control-label" ) }}
                        {{ form.server_name( class="form-control", value="" ) }}
                    </div>
                    <div class="form-row">
                        {{ form.endpoint_url.label( class="form-control-label" ) }}
                        <div class="input-goup">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroupPrepend">ocp.tcp://</span>
                                {{ form.endpoint_url(class="form-control", value="") }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        {{ form.namespace.label( class="form-control-label" ) }}
                        {{ form.namespace( class="form-control",value="" ) }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>

<!-- Start Server Modal -->
<div class="modal fade config-server-modal" style="margin: 10px;" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="POST" id="config-server-form" class="mx-3 mt-2 mb-3">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Config Server</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <!--Modal Title-->
                <div class="modal-body">
                    <div id="msgs"></div>
                    <input type="hidden" id="start_server_csrf" />
                    <input type="hidden" name="serverID" />
                    <div class="form-group">
                        <label for="input-ip">PLC Address</label>
                        <input type="text" id="input-ip" class="form-control" name="plc_ip"
                            placeholder="default: 192.168.0.1">
                    </div>
                </div>
                <div class="modal-footer">
                    <a data-server-id="" class="btn btn-sm btn-primary start-server" href="#"><i
                            data-feather="play-circle"></i></a>
                    <a data-server-id="" class="btn btn-sm btn-danger stop-server" href="#"> <i
                            data-feather="stop-circle"></i> </a>

                    <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button> -->
            </form>
        </div>
    </div>
</div>
</div>

<form id="projects_form" style="margin: 10px;" class="d-block mb-3" method="post" action="{{url_for('opcua_.create_server')}}"
    autocomplete=false>
    {{ form.hidden_tag() }}
    <div class="form-row">
        <div class="col-4 mb-3">
            {{ form.server_name.label( class="form-control-label" ) }}
            {{ form.server_name( class="form-control", value="" ) }}
        </div>

        <div class="col-4 mb-3">
            {{ form.endpoint_url.label( class="form-control-label" ) }}
            <div class="input-goup">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupPrepend">ocp.tcp://</span>
                    {{ form.endpoint_url(class="form-control", value="") }}
                </div>
            </div>
        </div>

        <div class="col-4 mb-3">
            {{ form.namespace.label( class="form-control-label" ) }}
            {{ form.namespace( class="form-control",value="" ) }}
        </div>
    </div>

    <div class="form-row">
        {{ form.submit( class="form-control btn btn-outline-info col-6 offset-3" ) }}
    </div>
</form>
<table class="table">
    <thead>
        <tr class="row">
            <th scope="col" class="col-sm-1">#</th>
            <th scope="col" class="col-sm-2">Server Name</th>
            <th scope="col" class="col-sm-2 ">Endpont Url</th>
            <th scope="col" class="col-sm-3 ">Namespace</th>
            <th scope="col" class="col-sm-3">Action</th>
        </tr>
    </thead>
    <tbody>
        {% if servers %}
        {% for server in servers %}
        <tr class="row">
            <th scope="row" class="col-sm-1">{{ server.id }}</th>
            <td class="col-sm-2">{{ server.server_name }}</td>
            <td class="col-sm-2">{{ server.server_endpoint_url }}</td>
            <td class="col-sm-3">{{ server.server_namespace }}</td>
            <td class="col-sm-3">
                <p>
                    <a data-serverid="{{ server.id }}" data-name="{{ server.server_name }}"
                        data-epurl="{{ server.server_endpoint_url }}" data-namespace="{{ server.server_namespace }}"
                        href="#" class="btn btn-success btn-sm edit-server-btn"> <i data-feather="edit-2"></i> </a>
                    <a class="btn btn-sm btn-secondary"
                        href="{{ url_for('opcua_.server_populate',serverid=server.id) }}"><i data-feather="edit"></i>
                    </a>
                    <a data-server-id="{{ server.id }}" data-toggle="modal" data-target=".config-server-modal"
                        class="btn btn-sm btn-info config-server" href="#"> <i data-feather="settings"></i> </a>
                    <a data-server="{{ server.id }}" role="button" class="btn btn-sm btn-warning delete-server"
                        href="#"><i data-feather="trash"></i></a>
                </p>
            </td>
        </tr>
        <form method="post" id="del-server-form-{{ server.id }}" class="d-none"
            action="{{ url_for('opcua_.delete_server',serverid=server.id) }}">
            <!-- <input type="hidden" name="csrf_token" value="f1d9d48ec0e26e2a250839fa36ea2c602cc4f85ccfeb5c65"/>
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              <input type="hidden" name="server_id" value="{{ server.id }}"> -->
        </form>
        {% endfor %}
        {% else %}
        <tr>
            <td class="text-center h3 text-muted"> <strong> No Servers Defined </strong></td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock %}

<!-- {% block javascripts %}-->
<!-- {{ super() }}
    <script>
        $('.delete-server').on('click',function(e){
            e.preventDefault()
            let serverid = $(this).attr('data-server');
            $('#del-server-form-'+serverid).trigger('submit') 
        });
        let csrf_token = "{{ csrf_token() }}"
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            }
        });
       
    </script> -->
<!-- {% endblock %} -->